### ISSUE TITLE
python pipeline_model_gat.py ：the relations between pickle and toechtext 

### ISSUE THREAD

**Issue by taingload** [codexxxl/GraphVQA#2]
when I run 
 `python pipeline_model_gat.py`
I get a error :
`Traceback (most recent call last):
  File "pipeline_model_gat.py", line 850, in <module>
    load_vocab_flag=True
  File "/home/tangting/repo/GraphVQA/gqa_dataset_entry.py", line 468, in __init__
    self.load_qa_vocab()
  File "/home/tangting/repo/GraphVQA/gqa_dataset_entry.py", line 578, in load_qa_vocab
    text_reloaded = pickle.load(f)
ModuleNotFoundError: No module named 'torchtext.data.field'
`

but found not 'torch.data.field' in this position ?

**Comment by codexxxl** [comment]
Looks like it may be your torchtext’s issue. Can you double check if you have successfully installed torchtext module as instructed in Usage 0.1?

**Comment by taingload** [comment]
> Looks like it may be your torchtext’s issue. Can you double check if you have successfully installed torchtext module as instructed in Usage 0.1?

my torchtext version is 0.10.0，and my torch version is 1.9.0
I use `pip install torch` and `pip install torchtext` to install it.

torch                    1.9.0
torch-cluster            1.5.9
torch-geometric          1.7.1
torch-scatter            2.0.7
torch-sparse             0.6.10
torch-spline-conv        1.2.1
torchtext                0.10.0
torchvision              0.2.1

**Comment by codexxxl** [comment]
Can you open a python session and try if you could directly import that missing module?

And here’s one of our virtual env’s package versions:
Try if torch==1.6.0, torchtext==0.7.0 would work for you too.

torch-cluster             1.5.9                     <pip>
torch-geometric           1.6.3                     <pip>
torch-scatter             2.0.6                     <pip>
torch-sparse              0.6.8                     <pip>
torch-spline-conv         1.2.1                     <pip>
torchtext                 0.7.0                      py37    pytorch
pytorch                   1.6.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch

**Comment by taingload** [comment]
> Can you open a python session and try if you could directly import that missing module?
> 
> And here’s one of our virtual env’s package versions:
> Try if torch==1.6.0, torchtext==0.7.0 would work for you too.
> 
> torch-cluster 1.5.9
> torch-geometric 1.6.3
> torch-scatter 2.0.6
> torch-sparse 0.6.8
> torch-spline-conv 1.2.1
> torchtext 0.7.0 py37 pytorch
> pytorch 1.6.0 py3.7_cuda10.1.243_cudnn7.6.3_0 pytorch

**Thank you so much,I change my package version to your version, and now can run without error**

I guess  there may be a trouble in torchtext so that  one package can't run success .

**Comment by taingload** [comment]
> Can you open a python session and try if you could directly import that missing module?
> 
> And here’s one of our virtual env’s package versions:
> Try if torch==1.6.0, torchtext==0.7.0 would work for you too.
> 
> torch-cluster 1.5.9
> torch-geometric 1.6.3
> torch-scatter 2.0.6
> torch-sparse 0.6.8
> torch-spline-conv 1.2.1
> torchtext 0.7.0 py37 pytorch
> pytorch 1.6.0 py3.7_cuda10.1.243_cudnn7.6.3_0 pytorch

Sorry,I meet a new error about torchvision, can I get your torchvision version?

`Traceback (most recent call last):
  File "mainExplain_gat.py", line 46, in <module>
    import util.misc as utils
  File "/home/***/GraphVQA/util/misc.py", line 22, in <module>
    from torchvision.ops import _new_empty_tensor
ModuleNotFoundError: No module named 'torchvision.ops'`

**Comment by codexxxl** [comment]
> > Can you open a python session and try if you could directly import that missing module?
> > And here’s one of our virtual env’s package versions:
> > Try if torch==1.6.0, torchtext==0.7.0 would work for you too.
> > torch-cluster 1.5.9
> > torch-geometric 1.6.3
> > torch-scatter 2.0.6
> > torch-sparse 0.6.8
> > torch-spline-conv 1.2.1
> > torchtext 0.7.0 py37 pytorch
> > pytorch 1.6.0 py3.7_cuda10.1.243_cudnn7.6.3_0 pytorch
> 
> **Thank you so much,I change my package version to your version, and now can run without error**
> 
> I guess there may be a trouble in torchtext so that one package can't run success .

We just found in torchtext version 0.9.0, there's a large change in its `data` module and the 'torchtext.data.field' became legacy. That's why you are getting this error message. 
Thank you for spotting this issue for us. We have updated the Readme to note this change.
