### ISSUE TITLE
What is the point assuming ground truth scene graphs are given?

### ISSUE THREAD

**Issue by coldmanck** [codexxxl/GraphVQA#3]
Hi @codexxxl thank you for your work & the code! I'd like to know that, most models for GQA assume no information other than raw images are available; however, you seem to have used ground truth scene graphs in the experiments. Shouldn't we try to generate scene graphs using, say, some existing scene graph generation methods to as part of the pipeline?

**Comment by codexxxl** [comment]
Hi @coldmanck, thank you for your interest and comment! The main purpose of this paper is to explore the design space of GNN on question answering tasks. So we chose to directly use the ground truth scene graphs to observe different effects. No matter what kind of generation methods are used, our ultimate goal would be focusing on the performance of GNN part.
