### ISSUE TITLE
Answer & Program Supervision

### ISSUE THREAD

**Issue by coldmanck** [codexxxl/GraphVQA#4]
Hi @codexxxl thank you for your great work! Could you please help to clarify the following questions:
1. In addition to question-answer supervision, you seem to also supervise program generation during training, as shown in the following code snippet:
https://github.com/codexxxl/GraphVQA/blob/8f2a13348776c0c7d80e527feda196eef310e0b4/mainExplain_gat.py#L540
However, according to the paper: "_We note that GraphVQA does not require any explicit supervision on how to solve the question step-by-step, and we only supervise on the final answer prediction._" Is there any misunderstanding here?

2. If you're really supervising program generation, what is the detail of the program generation module being used, as shown in the following code snippet?:
https://github.com/codexxxl/GraphVQA/blob/8f2a13348776c0c7d80e527feda196eef310e0b4/pipeline_model_gat.py#L317
Could you please provide any reference for this?

3. What are the `programs_input`, `programs_output`, `full_answers_input` and `full_answers_output` here? I also do not understand why programs & full answers inputs and targets are divided as follows:
https://github.com/codexxxl/GraphVQA/blob/8f2a13348776c0c7d80e527feda196eef310e0b4/pipeline_model_gat.py#L885-L888
It seems that inputs are almost equal to targets and only shift by 1 row. Could you please elaborate on this? Thank you!

**Comment by alice-cool** [comment]
Dear scholar, I run the 70th epoch ,I found all "Test:" print log is always 0.0 .

Generated Program (637): computer monitor sitting on sitting on jumping sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on younger Ground Truth Program (637): select ( ball )
Generated Program (638): computer monitor sitting on sitting on jumping sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on younger Ground Truth Program (638): exist ( [2] )
Generated Program (639): computer monitor sitting on sitting on jumping sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on younger Ground Truth Program (639): or ( [1], [3] )
Test: [ 0/661] Time 4.763 ( 4.763) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 94.50 ( 94.50)
Test: [ 50/661] Time 0.293 ( 0.383) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 90.50 ( 93.85)
Test: [100/661] Time 0.294 ( 0.340) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 95.50 ( 94.14)
Test: [150/661] Time 0.308 ( 0.325) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 95.00 ( 93.98)
Test: [200/661] Time 0.300 ( 0.318) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 92.50 ( 94.00)
Test: [250/661] Time 0.294 ( 0.313) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 96.00 ( 94.00)
Test: [300/661] Time 0.298 ( 0.310) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 95.50 ( 94.01)
Test: [350/661] Time 0.298 ( 0.308) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 94.00 ( 93.99)
Test: [400/661] Time 0.299 ( 0.307) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 94.00 ( 93.98)
Test: [450/661] Time 0.286 ( 0.305) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 95.00 ( 93.96)
Test: [500/661] Time 0.299 ( 0.304) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 95.00 ( 93.96)
Test: [550/661] Time 0.293 ( 0.304) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 94.00 ( 93.92)
Test: [600/661] Time 0.293 ( 0.303) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 94.50 ( 93.92)
Test: [650/661] Time 0.296 ( 0.302) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 97.50 ( 93.96)
Test: [660/661] Time 0.098 ( 0.302) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 96.77 ( 93.95)
Test: [661/661] Time 0.098 ( 0.302) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 96.77 ( 93.95)
Epoch: [70][ 0/4715] Time 4.50 (4.50) Data 4.12 (4.12) Loss 1.02e-01 (1.02e-01) Acc@Program 0.00 (0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty
