### ISSUE TITLE
Evaluation Issues

### ISSUE THREAD

**Issue by coldmanck** [codexxxl/GraphVQA#5]
Hi @codexxxl @Weixin-Liang I appreciate your help on my previously opened issues. I have other questions regarding how the evaluation is done:
- Why would you need this check & prediction padding mechanism? https://github.com/codexxxl/GraphVQA/blob/8f1c749447fdbce3c383bbdf13885b711ab3e198/eval.py#L152-L157
According to the official `eval.py` there's no this check here. If there's really any missing answer, I don't think it make sense to fill with some default answers and the reported numbers would also be invalid.
- According to the following two code snippets:
https://github.com/codexxxl/GraphVQA/blob/8f1c749447fdbce3c383bbdf13885b711ab3e198/eval.py#L139-L146
https://github.com/codexxxl/GraphVQA/blob/8f1c749447fdbce3c383bbdf13885b711ab3e198/eval.py#L250-L266
It seems your final output predictions miss some answers for the original validation "inferred" questions (`val_all_quesitons.json`). Am I right? Why does it happen, and why did you handle the missing like this? 

Many thanks, and I look forward to your reply!

**Comment by ZucksLiu** [comment]
HI @coldmanck, thanks for your careful review. We do appreciate your efforts on helping on this project!
As for your first question, this design is aiming to comtinue the evaluation process, as you can see if no prediction is geenrated, the original eval process will jump to a exception. You mentioned that using a default answer might not be a valid option, but we address that for all unpredictable questions, we use a same default answer, this is more like a backup design to let the evaluation through. We actually tried 'frog' as the default answer and don't see result numbers change much, you may try other default answers and see how answers change and welcome to share your results with us.
For your second question, it's mainly because some unawared bugs in the generation process of these question json files(we are still checking them), we leverage this design to avoid being annoyed by potential exceptions or errors. We thanks for your help again and hope this answer mught help you!

**Comment by alice-cool** [comment]
Dear scholar, I run the 70th epoch ,I found all "Test:" print log is always 0.0 .

Generated Program (637): computer monitor sitting on sitting on jumping sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on younger Ground Truth Program (637): select ( ball )
Generated Program (638): computer monitor sitting on sitting on jumping sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on younger Ground Truth Program (638): exist ( [2] )
Generated Program (639): computer monitor sitting on sitting on jumping sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on younger Ground Truth Program (639): or ( [1], [3] )
Test: [ 0/661] Time 4.763 ( 4.763) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 94.50 ( 94.50)
Test: [ 50/661] Time 0.293 ( 0.383) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 90.50 ( 93.85)
Test: [100/661] Time 0.294 ( 0.340) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 95.50 ( 94.14)
Test: [150/661] Time 0.308 ( 0.325) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 95.00 ( 93.98)
Test: [200/661] Time 0.300 ( 0.318) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 92.50 ( 94.00)
Test: [250/661] Time 0.294 ( 0.313) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 96.00 ( 94.00)
Test: [300/661] Time 0.298 ( 0.310) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 95.50 ( 94.01)
Test: [350/661] Time 0.298 ( 0.308) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 94.00 ( 93.99)
Test: [400/661] Time 0.299 ( 0.307) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 94.00 ( 93.98)
Test: [450/661] Time 0.286 ( 0.305) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 95.00 ( 93.96)
Test: [500/661] Time 0.299 ( 0.304) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 95.00 ( 93.96)
Test: [550/661] Time 0.293 ( 0.304) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 94.00 ( 93.92)
Test: [600/661] Time 0.293 ( 0.303) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 94.50 ( 93.92)
Test: [650/661] Time 0.296 ( 0.302) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 97.50 ( 93.96)
Test: [660/661] Time 0.098 ( 0.302) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 96.77 ( 93.95)
Test: [661/661] Time 0.098 ( 0.302) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 96.77 ( 93.95)
Epoch: [70][ 0/4715] Time 4.50 (4.50) Data 4.12 (4.12) Loss 1.02e-01 (1.02e-01) Acc@Program 0.00 (0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty
