### ISSUE TITLE
How to generate GQA_TEXT_obj.pkl?

### ISSUE THREAD

**Issue by qianqianderizi** [codexxxl/GraphVQA#8]
I can only use torchtext 0.9.0, so I need to generate this file. How to generate GQA_TEXT_obj.pkl? Thanks a lot.

**Comment by qianqianderizi** [comment]
The problem has been solved.
in gqa_dataset_entry.py line 462:
     # self.build_qa_vocab()
self.build_qa_vocab() can be used for generate. Put it in place.

**Comment by alice-cool** [comment]
Dear scholar, I run the 70th epoch ,I found all "Test:" print log is always 0.0 .

Generated Program (637): computer monitor sitting on sitting on jumping sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on younger Ground Truth Program (637): select ( ball )
Generated Program (638): computer monitor sitting on sitting on jumping sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on younger Ground Truth Program (638): exist ( [2] )
Generated Program (639): computer monitor sitting on sitting on jumping sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on sitting on younger Ground Truth Program (639): or ( [1], [3] )
Test: [ 0/661] Time 4.763 ( 4.763) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 94.50 ( 94.50)
Test: [ 50/661] Time 0.293 ( 0.383) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 90.50 ( 93.85)
Test: [100/661] Time 0.294 ( 0.340) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 95.50 ( 94.14)
Test: [150/661] Time 0.308 ( 0.325) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 95.00 ( 93.98)
Test: [200/661] Time 0.300 ( 0.318) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 92.50 ( 94.00)
Test: [250/661] Time 0.294 ( 0.313) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 96.00 ( 94.00)
Test: [300/661] Time 0.298 ( 0.310) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 95.50 ( 94.01)
Test: [350/661] Time 0.298 ( 0.308) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 94.00 ( 93.99)
Test: [400/661] Time 0.299 ( 0.307) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 94.00 ( 93.98)
Test: [450/661] Time 0.286 ( 0.305) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 95.00 ( 93.96)
Test: [500/661] Time 0.299 ( 0.304) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 95.00 ( 93.96)
Test: [550/661] Time 0.293 ( 0.304) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 94.00 ( 93.92)
Test: [600/661] Time 0.293 ( 0.303) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 94.50 ( 93.92)
Test: [650/661] Time 0.296 ( 0.302) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 97.50 ( 93.96)
Test: [660/661] Time 0.098 ( 0.302) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 96.77 ( 93.95)
Test: [661/661] Time 0.098 ( 0.302) Acc@Program 0.00 ( 0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty 0.00 (0.00) Acc@Short 96.77 ( 93.95)
Epoch: [70][ 0/4715] Time 4.50 (4.50) Data 4.12 (4.12) Loss 1.02e-01 (1.02e-01) Acc@Program 0.00 (0.00) Acc@ProgramGroup 0.00 (0.00) Acc@ProgramNonEmpty
